server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
  data:
    mongodb:
      database: delivery
      host: localhost
      port: 27017

oauth:
  auth:
    url: http://localhost:8081/oauth/authorize?client_id=web-client&response_type=code
  token:
    expire: 7200
    url: http://localhost:8081/oauth/token?grant_type=authorization_code&code=%s
    refresh:
      url: http://localhost:8081/oauth/token?grant_type=refresh_token&refresh_token=%s
  id:
    secret: d2ViLWNsaWVudDp3ZWItY2xpZW50LXNlY3JldA==